version: '3.3'
services:
  dev:
    build:
      args:
        NPM_REGISTRY_URL: ${NPM_REGISTRY_URL}
        ARTIFACTS_AUTH: ${ARTIFACTS_AUTH}
        ARTIFACTS_EMAIL: ${ARTIFACTS_EMAIL}
      cache_from:
        - node:10.14.0
        - stencil_dev:latest
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    extra_hosts:
      - docker:${DOCKER_PORT_2375_TCP_ADDR:-127.0.0.1}
    ports:
      - ${DEBUG_PORT:-9229}:9229         # Node.js Debugger
      - ${HTTP_SERVER_PORT:-5000}:5000   # Example HTTP Server
      - ${GRPC_SERVER_PORT:-50051}:50051 # Example GRPC Server
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src
      - node_modules:/usr/src/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
  prod:
    build:
      args:
        NPM_REGISTRY_URL: ${NPM_REGISTRY_URL}
      cache_from:
        - node:10.14.0-alpine
        - stencil:latest
      context: .
    env_file: .env
    ports:
      - ${HTTP_SERVER_PORT:-5000}:5000   # Example HTTP Server
      - ${GRPC_SERVER_PORT:-50051}:50051 # Example GRPC Server
    stdin_open: true
    tty: true
volumes:
  node_modules:
